apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-demo.fullname" . }}
  labels:
  {{ include "my-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "my-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
